### PR TITLE
Add and install active_admin

### PR DESCRIPTION
**Pull request by j0sv**
## PT: https://www.pivotaltracker.com/story/show/150783257 ##

Add gem active_admin and install the same

### CODE REVIEW

**Review by tochman — CHANGES_REQUESTED** [review]
No unit specs. Also, why du you use class name AdminUser? There are stories in the backlog about giving customers possibilities to create accounts. Why not create a more generic user class. Another question is about the Pundit gem. Why did you include it in this story? I don't see anything about authorization in this feature.

**Comment by j0sv** [comment]
Removed gem. Pundit was because of a misunderstanding when reading the documentation. 
A separate path for login was requested for admin users and admin user should not be able to login in the same log in function as the customer.

**Comment by j0sv** [comment]
Test for db model added.

**Review by tochman — APPROVED** [review]
I oppose use of a separate admin user class but it's not a blocker.

**Review by faraznaeem — APPROVED** [review]

**Pull request merged**
