### PR TITLE
Payment and delivery

### PR DESCRIPTION
**Pull request by j0sv**
## PT: https://www.pivotaltracker.com/story/show/150780352 ##

### CODE REVIEW

**Comment by tochman** [comment]
Good job. Please make use of i18n translations in the UI

**Comment by j0sv** [comment]
I will add i18n in the next feature implementation.

**Comment by tochman** [comment]
Alright, please make a separate feature in PT for it. This one is meargable IMO. @faraznaeem @caressahh @satorinic what are your thoughts?

**Review by satorinic — APPROVED** [review]
Looks fine

**Review by faraznaeem — APPROVED** [review]

**Pull request merged**
