### PR TITLE
Allow end user to select dishes and quantities

### PR DESCRIPTION
**Pull request by j0sv**
## PT: https://www.pivotaltracker.com/story/show/150780271 ##

- Add gems for testing javascript (poltergeist and phantomjs)
- Add test for selecting quantity of dishes.
- Add Next button.  
 
screencapture-localhost-3000-1504962346119

### CODE REVIEW

**Comment by tochman** [comment]
Is there a story for this in PT @j0sv ?

**Review by tochman — APPROVED** [review]
Nice job!

**Comment by tochman** [comment]
Is this one ready to go?

**Comment by j0sv** [comment]
@tochman Yes, I would say so.

**Pull request merged**
